jupyter_book_task:
  env:
    JULIA_VER: "1.8.1"
    JULIA_NUM_THREADS: "2"
    LC_ALL: "C"
    NJOBS: "2"
  auto_cancellation: true
  container:
    image: python:3.10-slim
    cpu: 2
    memory: 8G
  syspkg_script: apt-get update -q && apt-get install -qqy git parallel wget
  pypkg_script: |
    pip install -r requirements.txt -r .ci/requirements.txt
  install_julia_script: |
    wget https://raw.githubusercontent.com/abelsiqueira/jill/main/jill.sh
    bash jill.sh --version ${JULIA_VER} --yes
    julia --version
  julia_cache:
    folder: ~/.julia
    fingerprint_script: cat Manifest.toml
  jupkg_script: |
    julia --color=yes --project="" -e 'import Pkg; Pkg.add("IJulia"); Pkg.build("IJulia")'
    julia --color=yes --project=@. -e 'import Pkg; Pkg.instantiate()'
  execute_script: |
    parallel -j${NJOBS} jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace {} ::: docs/*.ipynb
  build_script: |
    jupyter-book build docs --warningiserror --keep-going -v
  # Requires a PAT `GH_TOKEN` with repo scope
  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     ghp-import -n docs/_build/html
  #     git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
  #   fi
